@startuml gantt
language fr
saturday are closed
sunday are closed
printscale daily zoom 2
' hide footbox
' hide ressources footbox

<style>
ganttDiagram {
	task {
		FontName Helvetica
		' FontColor red
		FontSize 12
		' FontStyle bold
		' BackGroundColor GreenYellow
		LineColor blue
	}
	milestone {
		FontColor blue
		FontSize 25
		FontStyle italic
		BackGroundColor yellow
		LineColor red
	}
	note {
		FontColor DarkGreen
		FontSize 10
		LineColor OrangeRed
	}
	arrow {
		FontName Helvetica
		FontColor red
		FontSize 18
		FontStyle bold
		BackGroundColor GreenYellow
		LineColor blue
		LineStyle 8.0;13.0
		LineThickness 3.0
	}
	separator {
		BackgroundColor lightGreen
		LineStyle 8.0;3.0
		LineColor red
		LineThickness 1.0
		FontSize 16
		FontStyle bold
		FontColor purple
		Margin 5
		Padding 5
	}
	timeline {
	    BackgroundColor Bisque
	}
	closed {
		BackgroundColor pink
		FontColor red
	}
}
</style>

Project starts 2022-04-11
' SPRINT I
-- SPRINT I --
[Init] as [I] starts 2022-04-11
[Parallelisation client] as [PC] starts 2022-04-12
[Parallelisation serveur] as [PS] starts 2022-04-12
[Fusion] as [F] starts 2022-04-12

[I] on {Lucas:100%} lasts 1 day
[F] on {Lucas:100%} lasts 1 day
[PS] on {Marvin:100%} lasts 3 days
[PC] on {Éri:100%} lasts 3 days

[I] -> [PC]
[I] -> [PS]
[PC] -> [F]
[PS] -> [F]


' SPRINT II
-- SPRINT II --
[Gestion multi-client] as [MCH] starts 2022-04-19 and lasts 4 days
[Message Privé] as [MP] starts 2022-04-19 and lasts 4 days
[Manuel] as [Help] starts 2022-04-25 and lasts 3 days
[Intégrité] as [Int] lasts 2 days
[Code review] as [CR] starts 2022-04-26 and lasts 4 days

[CR] on {Lucas:100%} lasts 4 days
[MCH] on {Lucas:100%} lasts 4 days
[MP] on {Marvin:50%} lasts 3 days
[Help] on {Éri:100%} lasts 3 days
' [Help] on {Marvin:100%} lasts 2 days
[Intégrité] on {Éri:100%} starts 2022-04-25 and lasts 2 days

[F] -> [MCH]
[F] -> [MP]
[MCH] -> [CR]
[MCH] -> [Int]
[MP] -> [Help]
[Int] -> [Help]
@enduml
