@startuml architecture
skinparam Linetype ortho

together {
	package Serveur {
		[serveur.c] as serv
		together {
			artifact sendFromAtoBThread
			artifact recvFromAtoBThread
		}
		serv -d-> sendFromAtoBThread
		serv -d-> recvFromAtoBThread
	}


	package Client {
		[ client.c ] as clix
		together {
			artifact sendThread as sendThread
			artifact recvThread as recvThread
		}
		clix -d-> sendThread
		clix -d-> recvThread
	}
}
interface TCP

TCP <-d-> Client
TCP <-d-> Serveur
@enduml