@startuml architecture

together {
	package Serveur.c as Server {
		package ClientThreads {
			component clientManagement as cx
		}

		artifact connectionParameters as param
		artifact semaphore as sem
		artifact mutex
		param <-- ClientThreads
		param --> sem
		param --> mutex

		note bottom of mutex 
		protection de la liste
		des clients
		end note
		note bottom of sem
		mise en sommeil lorsque
		le nombre de client max
		est atteint
		end note
	}


	package Client.c as Client {
		together {
			component sendThread as sendThread
			component recvThread as recvThread
		}
	}

	package Commandes.c as Commands {
		artifact help
		artifact mp

		note bottom of help
		send to the client
		the commands list
		end note

		note bottom of mp
		send a message to a
		specific user only
		end note
	}


}
interface TCP

TCP <--> Client
Client -[hidden]d- Commands 
Server <--> Commands
TCP <--> Server
@enduml