@startuml protocole

skinparam responseMessageBelowArrow true

actor Bob 
participant "Bob's client" as Client1
participant Server 
participant "Alice's client" as Client2
actor Alice
==Connexion (synchrone)==
autonumber "<b>[00]"
Bob -> Client1++: start
Client1 -> Server++: ask for connection
Server --> Client1: connection confirmation
Client1 --> Bob: ready
Alice -> Client2++: start
Client2 -> Server: ask for connection
Server --> Client2: connection confirmation
Client2 --> Alice: ready

==Échange de message (asynchrone)==

par
autonumber 0-0
Bob -> Client1 : write message
Client1 -> Server: transmit message's size
Client1 -> Server: transmit message
Server -> Client2: send message's size
Server -> Client2: send message
Client2 -> Alice: receive message
else
autonumber 1-0
Alice -> Client2--: write message
Client2 -> Server: transmit message's size
Client2 -> Server--: transmit message
Server -> Client1: send message's size
Server -> Client1--: send message
Client1 -> Bob--: receive message
end
@enduml